# This file is auto-generated by the dh-umc tools and should not be edited!
msgid ""
msgstr ""
"Project-Id-Version: univention-management-console-module-reboot\n"
"Report-Msgid-Bugs-To: packages@univention.de\n"
"POT-Creation-Date: 2016-01-14 12:15+0100\n"
"PO-Revision-Date: 2016-01-14 11:26+0100\n"
"Last-Translator: Univention GmbH <packages@univention.de>\n"
"Language-Team: Univention GmbH <packages@univention.de>\n"
"Language: de\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

#: umc/python/adtakeover/takeover.py:1917
msgid " failed"
msgstr " schlug fehl"

#: umc/python/adtakeover/takeover.py:811
#, python-format
msgid "AD Server did not return proper time string: %s."
msgstr ""
"Der Active Directory-Server lieferte eine unerwartete Zeitangabe zurück: %s."

#: umc/python/adtakeover/takeover.py:619
#, python-format
msgid "Active Directory services not detected at %s."
msgstr "Active Directory-Dienste sind nicht erreichbar über %s."

#: umc/python/adtakeover/takeover.py:1442
msgid "Active Directory takeover finished already."
msgstr "Active Directory Takeover ist schon abgeschlossen."

#: umc/python/adtakeover/takeover.py:327
msgid "Adjusting settings in Samba directory service"
msgstr "Anpassung von Einstellungen im Samba-Verzeichnisdienst"

#: umc/python/adtakeover/takeover.py:203
msgid ""
"At least one GPO in SYSVOL is newer than the Group Policy Container version."
msgstr ""
"Mindestens eine GPO im SYSVOL ist neuer als die Group Policy Container "
"Version."

#: umc/python/adtakeover/takeover.py:200
#: umc/python/adtakeover/takeover.py:1844
msgid "At least one GPO in SYSVOL is not up to date yet."
msgstr "Mindestens eine GPO im SYSVOL ist noch nicht aktuell."

#: umc/python/adtakeover/takeover.py:197
msgid "At least one GPO is still missing in SYSVOL."
msgstr "Mindestens eine GPO fehlt noch im SYSVOL."

#: umc/python/adtakeover/takeover.py:243 umc/python/adtakeover/takeover.py:270
msgid "Authenticating"
msgstr "Authentifizierung"

#: umc/python/adtakeover/takeover.py:191
msgid "Authentication failed."
msgstr "Authentifizierung fehlgeschlagen."

#: umc/python/adtakeover/takeover.py:382
msgid "Checking GPOs in SYSVOL"
msgstr "Prüfung der GPO-Daten im SYSVOL"

#: umc/python/adtakeover/takeover.py:291
msgid "Checking group policies"
msgstr "Prüfung der Gruppenrichtlinien"

#: umc/python/adtakeover/takeover.py:331
msgid "Claiming FSMO roles"
msgstr "Übernahme der FSMO-Rollen"

#: umc/python/adtakeover/takeover.py:240 umc/python/adtakeover/takeover.py:266
#, python-format
msgid "Connecting to %s"
msgstr "Verbindung zu %s"

#: umc/python/adtakeover/takeover.py:1953
#, python-format
msgid "Connection to Active Directory server %s failed."
msgstr "Die Verbindung zum Active Directory-Server %s schlug fehl."

#: umc/python/adtakeover/takeover.py:926 umc/python/adtakeover/takeover.py:936
#, python-format
msgid "Copying %s"
msgstr "Kopiere %s"

#: umc/python/adtakeover/takeover.py:908
#, python-format
msgid "Could not read local machine password: %s"
msgstr "Interner Fehler beim Lesen des Maschinenpassworts: %s"

#: umc/python/adtakeover/takeover.py:194
msgid "Domain join failed."
msgstr "Der Domänenbeitritt schlug fehl."

#: umc/python/adtakeover/__init__.py:69
#, python-format
msgid ""
"Execution of command '%(command)s' has failed:\n"
"\n"
"%(text)s"
msgstr ""
"Die Ausführung des Kommandos '%(command)s' ist fehlgeschlagen:\n"
"\n"
"%(text)s"

#: umc/python/adtakeover/takeover.py:1986
msgid "Faild to detect the Active Directory site of the server."
msgstr ""
"Die Erkennung des Active Directory-Standorts (site) des Servers schlug fehl."

#: umc/python/adtakeover/takeover.py:671
msgid "Failed to determine AD domain SID."
msgstr "Die SID der AD-Domäne konnte nicht festgestellt werden."

#: umc/python/adtakeover/takeover.py:1015
msgid "Failed to determine new domain SID."
msgstr "Die neue Domänen-SID konnte nicht festgestellt werden."

#: umc/python/adtakeover/takeover.py:353
msgid "Finalizing"
msgstr "Abschluss"

#: umc/python/adtakeover/takeover.py:293
msgid "Initializing the S4 Connector listener"
msgstr "Initialisierung des S4 Connector Listeners"

#: umc/python/adtakeover/takeover.py:218
msgid "Insufficient License."
msgstr "Die Lizenz reicht nicht aus."

#: umc/python/adtakeover/takeover.py:566
msgid "Internal Error: License check failed."
msgstr "Interner Fehler bei der Prüfung der Lizenz."

#: umc/python/adtakeover/takeover.py:832
#, python-format
msgid "Internal Error: rdate -s -p failed (%d)."
msgstr "Internal Error: rdate -s -p schlug fehl (%d)."

#: umc/python/adtakeover/takeover.py:426
#, python-format
msgid ""
"Internal module error: Cannot go from state '%(current)s' to state '%(new)s'."
msgstr ""
"Interner Modulfehler: Übergang von Status '%(current)s' zu Status '%(new)s' ist nicht "
"möglich."

#: umc/python/adtakeover/takeover.py:431
#, python-format
msgid ""
"Internal module error: Expected to be in state 'sysvol', but found '%s'."
msgstr "Interner Modulfehler: Zustand 'sysvol' erwartet, aber '%s' gefunden."

#: umc/python/adtakeover/takeover.py:436
#, python-format
msgid ""
"Internal module error: Expected to be in state 'takeover', but found '%s'."
msgstr "Interner Modulfehler: Zustand 'takeover' erwartet, aber '%s' gefunden."

#: umc/python/adtakeover/takeover.py:409
#, python-format
msgid "Internal module error: Refusing to set invalid state '%s'."
msgstr "Interner Modulfehler: Setzen des ungültigen Status '%s' abgelehnt."

#: umc/python/adtakeover/takeover.py:441
msgid "Internal module error: Takeover running, aborting attempt to restart."
msgstr "Interner Modulfehler: Takeover läuft, Neustartversuch abgebrochen."

#: umc/python/adtakeover/takeover.py:2429
#, python-format
msgid "Invalid UNC string: %s"
msgstr "Ungültiger UNC-Pfad: %s"

#: umc/python/adtakeover/takeover.py:468
#, python-format
msgid "Invalid state in file %s"
msgstr "Ungültige Zustands-Datei %s"

#: umc/python/adtakeover/takeover.py:279
msgid "Joining the domain"
msgstr "Domänenbeitritt"

#: umc/python/adtakeover/takeover.py:1920
#, python-format
msgid "Network connection to %s failed."
msgstr "Netzwerkverbindung zu %s schlug fehl."

#: umc/python/adtakeover/takeover.py:590
#, python-format
msgid ""
"Number of %(object_name)s after takeover would be %(sum)s. This would exceed "
"the number of licensed objects (%(max)s)."
msgstr ""
"Anzahl der %(object_name)s nach dem Takeover wäre %(sum)s. Das übersteigt "
"die Anzahl an lizenzierten Objekten (%(max)s)."

#: umc/python/adtakeover/takeover.py:301
msgid "Rebuilding IDMAP"
msgstr "Erstellung der IDMAP-Tabelle"

#: umc/python/adtakeover/takeover.py:350
msgid "Reconfiguring nameserver"
msgstr "Rekonfigurierung des Nameservers"

#: umc/python/adtakeover/takeover.py:347
msgid "Registering IP in DNS"
msgstr "Registrierung der IP im DNS"

#: umc/python/adtakeover/takeover.py:821
#, python-format
msgid ""
"Remote clock is behind local clock by more than %s seconds, refusing to turn "
"back time. Please advance the clock of the Active Directory DC."
msgstr ""
"Die Uhr des Active Directory-Servers liegt hinter der lokalen Zeit um mehr "
"als %s Sekunden zurück. Die lokale Zeit kann nicht zurückgestellt werden. "
"Bitte stellen Sie die Zeit am Active Directory-DC vor."

#: umc/python/adtakeover/takeover.py:334
msgid "Removing the previous AD server account"
msgstr "Entfernen des alten AD Server-Kontos"

#: umc/python/adtakeover/takeover.py:304
msgid "Reset SYSVOL ACLs"
msgstr "Initialisierung der SYSVOL-ACLs"

#: umc/python/adtakeover/takeover.py:246
msgid "Retrieving information from AD DC"
msgstr "Abfrage von Informationen vom AD-DC"

#: umc/python/adtakeover/takeover.py:288
msgid "Rewriting SIDs in the UCS directory service"
msgstr "Umschreibung der SIDs im UCS Verzeichnisdienst"

#: umc/python/adtakeover/takeover.py:321
#, python-format
msgid "Search for %s in network"
msgstr "Netzwerksuche nach %s"

#: umc/python/adtakeover/takeover.py:206
msgid "Something is wrong with the SYSVOL."
msgstr "Etwas stimmt nicht mit dem SYSVOL."

#: umc/python/adtakeover/takeover.py:285
msgid "Starting Samba"
msgstr "Start von Samba"

#: umc/python/adtakeover/takeover.py:297
msgid "Starting the S4 Connector"
msgstr "Start des S4 Connectors"

#: umc/python/adtakeover/takeover.py:274
msgid "Synchronizing system clock"
msgstr "Synchronisation der Systemzeit"

#: umc/python/adtakeover/takeover.py:326
msgid "Taking over Active Directory domain controller roles"
msgstr "Übernahme der Active Directory Domänencontroller-Rollen"

#: umc/python/adtakeover/takeover.py:338
msgid "Taking over DNS address"
msgstr "Übernahme der DNS-Adresse"

#: umc/python/adtakeover/takeover.py:344
msgid "Taking over IP address"
msgstr "Übernahme der IP-Adresse"

#: umc/python/adtakeover/takeover.py:341
msgid "Taking over NETBIOS address"
msgstr "Übernahme der NETBIOS-Adresse"

#: umc/python/adtakeover/takeover.py:667
#, python-format
msgid ""
"The Active Directory domain has a function level of Windows Server 2012 or "
"newer, Samba currently only supports up to Windows 2008R2: %s"
msgstr ""
"Die Active Directory Domäne hat einen Funktionslevel von Windows Server 2012 "
"oder neuer, Samba unterstützt momentan nur bis Windows 2008R2: %s"

#: umc/python/adtakeover/takeover.py:1415
#: umc/python/adtakeover/takeover.py:1423
msgid "The Active Directory domain join was not completed successfully yet."
msgstr ""
"Der Beitritt zur Active Directory Domäne wurde noch nicht erfolgreich "
"abgeschlossen."

#: umc/python/adtakeover/takeover.py:209
msgid "The Active Directory server seems to be running. It must be shut off."
msgstr ""
"Es scheint, als ob der Active Directory Server noch liefe. Er muss "
"ausgeschaltet werden."

#: umc/python/adtakeover/takeover.py:652
msgid ""
"The LDAP base of this UCS domain differs from the LDAP base of the selected "
"Active Directory domain."
msgstr ""
"Die LDAP-Basis dieser UCS Domäne unterscheidet sich von der LDAP-Basis der "
"ausgewählten Active Directory-Domäne."

#: umc/python/adtakeover/takeover.py:1467
#, python-format
msgid "The Server IP %s is still online, please shut down the machine."
msgstr ""
"Die Server IP %s ist noch online, die Maschine sollte ausgeschaltet werden."

#: umc/python/adtakeover/takeover.py:1962
#, python-format
msgid ""
"The automatic search for an Active Directory server for realm %s did not "
"yield any results."
msgstr ""
"Die automatische Suche eines Active Directory Servers für den Kerberos-Realm "
"%s lieferte keine Ergebnisse."

#: umc/python/adtakeover/takeover.py:188
msgid "The computer is not reachable."
msgstr "Der Rechner ist nicht erreichbar."

#: umc/python/adtakeover/takeover.py:857 umc/python/adtakeover/takeover.py:947
#: umc/python/adtakeover/takeover.py:995
#, python-format
msgid "The domain join failed. See %s for details."
msgstr ""
"Der Domänenbeitritt schlug fehl, die Logdatei %s enthält genauere Details."

#: umc/python/adtakeover/takeover.py:647
msgid ""
"The selected Active Directory server has the same NTDS GUID as this UCS "
"server."
msgstr ""
"Der angegebene Active Directory-Server hat die gleiche NTDS GUID wie dieser "
"UCS Server."

#: umc/python/adtakeover/takeover.py:215
msgid "Time difference critical for Kerberos but synchronization aborted."
msgstr ""
"Die Zeitdifferenz ist zu groß für Kerberos, aber die Synchronisierung schlug "
"fehl."

#: umc/python/adtakeover/takeover.py:212
msgid "Time synchronization failed."
msgstr "Die Zeitsynchronisierung schlug fehl."

#: umc/python/adtakeover/takeover.py:2422
msgid "UNC doesn't start with \\\\ or //"
msgstr "UNC-Pfad startet nicht mit \\\\ oder //"

#: umc/python/adtakeover/takeover.py:251
msgid ""
"You may proceed with the takeover, but the domain management may be limited "
"afterwards until a new license is installed."
msgstr ""
"Der Takeover kann fortgeführt werden, aber die Domäne kann danach womöglich "
"nur eingeschränkt verwaltet werden, bis eine neue Lizenz installiert wird."

#: umc/python/adtakeover/takeover.py:577
msgid "users"
msgstr "Benutzer"
